version: '3'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  webapi:
    build: .
    environment:
      DbPort: "1433"
      DbUser: "SA"
      Password: "yourStrong(!)Password"
      Database: "master"
    ports: 
      - "8090:80"