version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - "./mssql/data/:/var/opt/mssql/data/"
      - "./mssql/log/:/var/opt/mssql/log/"
      - "./mssql/secrets/:/var/opt/mssql/secrets/"

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DbPort: "1433"
      DbUser: "SA"
      Password: "yourStrong(!)Password"
      Database: "master"
    ports: 
      - "5000:80"